/****** Object:  Index [GST_UPLOAD_ERROR_STATUS_01]    Script Date: 2/21/2023 10:17:49 AM ******/
DROP INDEX [GST_UPLOAD_ERROR_STATUS_01] ON [dbo].[GST_UPLOAD_ERROR_STATUS]
GO

/****** Object:  Table [dbo].[GST_UPLOAD_ERROR_STATUS]    Script Date: 2/21/2023 10:17:49 AM ******/
DROP TABLE [dbo].[GST_UPLOAD_ERROR_STATUS]
GO

/****** Object:  Table [dbo].[GST_UPLOAD_ERROR_STATUS]    Script Date: 2/21/2023 10:17:49 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[GST_UPLOAD_ERROR_STATUS](
	[CCOMPANY_ID] [varchar](10) NOT NULL,
	[CUSER_ID] [varchar](20) NOT NULL,
	[CKEY_GUID] [varchar](40) NOT NULL,
	[ISEQ_NO] [int] NOT NULL,
	[IERROR_SEQ_NO] [bigint] IDENTITY(1,1) NOT NULL,
	[CERROR_MESSAGE] [varchar](500) NOT NULL,
 CONSTRAINT [PK_GST_UPLOAD_ERROR_STATUS_1] PRIMARY KEY CLUSTERED 
(
	[IERROR_SEQ_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

SET ANSI_PADDING ON

GO

/****** Object:  Index [GST_UPLOAD_ERROR_STATUS_01]    Script Date: 2/21/2023 10:17:49 AM ******/
CREATE NONCLUSTERED INDEX [GST_UPLOAD_ERROR_STATUS_01] ON [dbo].[GST_UPLOAD_ERROR_STATUS]
(
	[CCOMPANY_ID] ASC,
	[CUSER_ID] ASC,
	[CKEY_GUID] ASC,
	[ISEQ_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


