/****** Object:  Table [dbo].[GST_SPLIT_UPLOAD]    Script Date: 2/21/2023 10:17:16 AM ******/
DROP TABLE [dbo].[GST_SPLIT_UPLOAD]
GO

/****** Object:  Table [dbo].[GST_SPLIT_UPLOAD]    Script Date: 2/21/2023 10:17:16 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[GST_SPLIT_UPLOAD](
	[CCOMPANY_ID] [varchar](10) NOT NULL,
	[CUSER_ID] [varchar](20) NOT NULL,
	[CKEY_GUID] [varchar](40) NOT NULL,
	[ISEQ_NO] [int] NOT NULL,
	[ODATA] [varbinary](max) NOT NULL,
	[DCREATE_DATE] [date] NOT NULL CONSTRAINT [DF_GST_SPLIT_UPLOAD_DCREATE_DATE]  DEFAULT (getdate()),
 CONSTRAINT [PK_GST_SPLIT_UPLOAD] PRIMARY KEY CLUSTERED 
(
	[CCOMPANY_ID] ASC,
	[CUSER_ID] ASC,
	[CKEY_GUID] ASC,
	[ISEQ_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


